### ISSUE TITLE
Upload failed.

### ISSUE THREAD

**Issue by waterWang** [clxy/BigFileUploadJava#1]
您好，请问Config.java中的url是目标路径吗？ 

![Uploading QQ截图20151127231249.jpg…]()

**Comment by clxy** [comment]
是的。后台接收文件的程序地址

**Comment by wangbaoyin** [comment]
您好，请问一下您那个url是上传到服务器存储目录地址吗，我配置了一个虚拟目录，通过http可以访问的，为什么上传失败呢，

**Comment by clxy** [comment]
你好，不是存储目录地址，服务器接收文件的url。
比如，UploadAction的url映射。

参考下我的服务器端实现吧
https://github.com/clxy/SSM/blob/master/src/main/java/cn/clxy/ssm/common/action/UploadAction.java
